/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type {
  CreateQuestionEventBody,
  CreateQuestionRequest,
  CreateQuestionResponse,
  CreateUserExpertiseRequest,
  CreateUserHookRequest,
  CreateUserRequest,
  FinishConsultationRequest,
  GetQuestionConfigurationsResponse,
  GetUserExpertiseResponse,
  GetUserNotificationResponse,
  GetUserResponse,
  HighlightSectionsResponse,
  MobileQuestionEventMessageSent,
  Question,
  QuestionOutput,
  UpdateUserExpertiseRequest,
  UpdateUserRequest,
  UploadFileForQuestionBody,
  UploadFileForQuestionParams,
  UploadQuestionFileResponse,
} from "./models"
import { apiRequest } from "../api/api"

/**
 * @summary Highlight each sections
 */
export const highlightSections = () => {
  return apiRequest<HighlightSectionsResponse>({
    url: `/question/aggregate/highlight-sections`,
    method: "GET",
  })
}

export const createQuestion = (createQuestionRequest: CreateQuestionRequest) => {
  return apiRequest<CreateQuestionResponse>({
    url: `/question`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createQuestionRequest,
  })
}

export const getQuestionConfigurations = () => {
  return apiRequest<GetQuestionConfigurationsResponse>({
    url: `/question/configurations`,
    method: "GET",
  })
}

export const getQuestionById = (id: string) => {
  return apiRequest<QuestionOutput>({ url: `/question/${id}`, method: "GET" })
}

export const getQuestionByUser = (user: string) => {
  return apiRequest<QuestionOutput>({ url: `/question/user/${user}`, method: "GET" })
}

/**
 * @summary Create a question event
 */
export const createQuestionEvent = (
  questionId: string,
  createQuestionEventBody: CreateQuestionEventBody,
) => {
  return apiRequest<QuestionOutput>({
    url: `/question/${questionId}/event`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createQuestionEventBody,
  })
}

/**
 * @summary Finish consultation
 */
export const finishConsultation = (
  id: string,
  finishConsultationRequest: FinishConsultationRequest,
) => {
  return apiRequest<void>({
    url: `/question/${id}/finish`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: finishConsultationRequest,
  })
}

/**
 * @summary List question events for mobile devices
 */
export const listMobileQuestionEvents = (id: string) => {
  return apiRequest<MobileQuestionEventMessageSent[]>({
    url: `/question/mobile/${id}/events`,
    method: "GET",
  })
}

/**
 * @summary Take consultation
 */
export const pickQuestion = (id: string) => {
  return apiRequest<Question>({ url: `/question/${id}/pick`, method: "POST" })
}

/**
 * @summary Accept question
 */
export const acceptQuestion = (id: string) => {
  return apiRequest<void>({ url: `/question/${id}/accept`, method: "POST" })
}

/**
 * @summary List community questions
 */
export const listCommunityQuestions = () => {
  return apiRequest<Question[]>({ url: `/question/list/community`, method: "GET" })
}

/**
 * @summary List my questions
 */
export const listMyQuestions = () => {
  return apiRequest<Question[]>({ url: `/question/list/mine`, method: "GET" })
}

export const seedMetadata = () => {
  return apiRequest<void>({ url: `/question/suportdeveloper/seedmetadata`, method: "POST" })
}

export const getAgencyPortal = () => {
  return apiRequest<void>({ url: `/agency-portal`, method: "GET" })
}

export const uploadFileForQuestion = (
  questionId: string,
  uploadFileForQuestionBody: UploadFileForQuestionBody,
  params: UploadFileForQuestionParams,
) => {
  const formData = new FormData()
  formData.append("file", uploadFileForQuestionBody.file)

  return apiRequest<UploadQuestionFileResponse>({
    url: `/file/question/${questionId}`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    params,
  })
}

export const createUser = (createUserRequest: CreateUserRequest) => {
  return apiRequest<void>({
    url: `/user`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createUserRequest,
  })
}

export const getCurrentUser = () => {
  return apiRequest<GetUserResponse>({ url: `/user`, method: "GET" })
}

export const updateUser = (updateUserRequest: UpdateUserRequest) => {
  return apiRequest<void>({
    url: `/user`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateUserRequest,
  })
}

export const createUserAction = (createUserHookRequest: CreateUserHookRequest) => {
  return apiRequest<void>({
    url: `/user/oauth0/create`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createUserHookRequest,
  })
}

export const createUserExpertise = (createUserExpertiseRequest: CreateUserExpertiseRequest) => {
  return apiRequest<void>({
    url: `/user/expertise`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createUserExpertiseRequest,
  })
}

export const getUserExpertise = () => {
  return apiRequest<GetUserExpertiseResponse[]>({ url: `/user/expertise`, method: "GET" })
}

export const updateUserExpertise = (updateUserExpertiseRequest: UpdateUserExpertiseRequest) => {
  return apiRequest<void>({
    url: `/user/expertise`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateUserExpertiseRequest,
  })
}

export const getCurrentUserContacts = () => {
  return apiRequest<GetUserExpertiseResponse[]>({ url: `/user/contact`, method: "GET" })
}

export const getUserNotification = () => {
  return apiRequest<GetUserNotificationResponse[]>({ url: `/user/Notifications`, method: "GET" })
}

export type HighlightSectionsResult = NonNullable<Awaited<ReturnType<typeof highlightSections>>>
export type CreateQuestionResult = NonNullable<Awaited<ReturnType<typeof createQuestion>>>
export type GetQuestionConfigurationsResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionConfigurations>>
>
export type GetQuestionByIdResult = NonNullable<Awaited<ReturnType<typeof getQuestionById>>>
export type GetQuestionByUserResult = NonNullable<Awaited<ReturnType<typeof getQuestionByUser>>>
export type CreateQuestionEventResult = NonNullable<Awaited<ReturnType<typeof createQuestionEvent>>>
export type FinishConsultationResult = NonNullable<Awaited<ReturnType<typeof finishConsultation>>>
export type ListMobileQuestionEventsResult = NonNullable<
  Awaited<ReturnType<typeof listMobileQuestionEvents>>
>
export type PickQuestionResult = NonNullable<Awaited<ReturnType<typeof pickQuestion>>>
export type AcceptQuestionResult = NonNullable<Awaited<ReturnType<typeof acceptQuestion>>>
export type ListCommunityQuestionsResult = NonNullable<
  Awaited<ReturnType<typeof listCommunityQuestions>>
>
export type ListMyQuestionsResult = NonNullable<Awaited<ReturnType<typeof listMyQuestions>>>
export type SeedMetadataResult = NonNullable<Awaited<ReturnType<typeof seedMetadata>>>
export type GetAgencyPortalResult = NonNullable<Awaited<ReturnType<typeof getAgencyPortal>>>
export type UploadFileForQuestionResult = NonNullable<
  Awaited<ReturnType<typeof uploadFileForQuestion>>
>
export type CreateUserResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
export type GetCurrentUserResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>
export type UpdateUserResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
export type CreateUserActionResult = NonNullable<Awaited<ReturnType<typeof createUserAction>>>
export type CreateUserExpertiseResult = NonNullable<Awaited<ReturnType<typeof createUserExpertise>>>
export type GetUserExpertiseResult = NonNullable<Awaited<ReturnType<typeof getUserExpertise>>>
export type UpdateUserExpertiseResult = NonNullable<Awaited<ReturnType<typeof updateUserExpertise>>>
export type GetCurrentUserContactsResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserContacts>>
>
export type GetUserNotificationResult = NonNullable<Awaited<ReturnType<typeof getUserNotification>>>
