/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type {
  CreateQuestionEventBody,
  CreateQuestionEventResponse,
  CreateQuestionRequest,
  CreateQuestionResponse,
  CreateUserExpertiseRequest,
  FinishConsultationRequest,
  GetQuestionConfigurationsResponse,
  GetRecentQuestionsParams,
  GetUserExpertiseResponse,
  GetUserHighlightsResponse,
  GetUserNotificationResponse,
  GetUserResponse,
  MobileQuestionEventMessageSent,
  Question,
  QuestionBriefPaginationResponse,
  UpdateUserExpertiseRequest,
  UpdateUserRequest,
  UploadFileResponse,
  UploadQuestionFileParams,
} from "./models"
import { apiRequest } from "../api/api"

/**
 * @summary Create a question event
 */
export const createQuestionEvent = (
  questionId: string,
  createQuestionEventBody: CreateQuestionEventBody,
) => {
  return apiRequest<CreateQuestionEventResponse>({
    url: `/mobile/questions/${questionId}/events`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createQuestionEventBody,
  })
}

/**
 * @summary List question events for mobile devices
 */
export const listMobileQuestionEvents = (questionId: string) => {
  return apiRequest<MobileQuestionEventMessageSent[]>({
    url: `/mobile/questions/${questionId}/events`,
    method: "GET",
  })
}

/**
 * @summary Create question
 */
export const createQuestion = (createQuestionRequest: CreateQuestionRequest) => {
  return apiRequest<CreateQuestionResponse>({
    url: `/mobile/questions`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createQuestionRequest,
  })
}

/**
 * @summary Finish consultation
 */
export const finishConsultation = (
  questionId: string,
  finishConsultationRequest: FinishConsultationRequest,
) => {
  return apiRequest<void>({
    url: `/mobile/questions/${questionId}:resolve`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: finishConsultationRequest,
  })
}

/**
 * @summary Get configurations for user
 */
export const getUserConfigurations = () => {
  return apiRequest<GetQuestionConfigurationsResponse>({
    url: `/mobile/questions/configurations`,
    method: "GET",
  })
}

/**
 * @summary Get highlights for user
 */
export const getUserHighlights = () => {
  return apiRequest<GetUserHighlightsResponse>({
    url: `/mobile/questions/aggregates/user-highlights`,
    method: "GET",
  })
}

/**
 * @summary List community questions
 */
export const listCommunityQuestions = () => {
  return apiRequest<Question[]>({ url: `/mobile/questions/sections/community`, method: "GET" })
}

/**
 * @summary List my questions
 */
export const listMyQuestions = () => {
  return apiRequest<Question[]>({ url: `/mobile/questions/sections/mine`, method: "GET" })
}

/**
 * @summary Get recent questions
 */
export const getRecentQuestions = (params: GetRecentQuestionsParams) => {
  return apiRequest<QuestionBriefPaginationResponse>({
    url: `/mobile/questions/sections/recent`,
    method: "GET",
    params,
  })
}

/**
 * @summary Take consultation
 */
export const pickQuestion = (questionId: string) => {
  return apiRequest<Question>({ url: `/mobile/questions/${questionId}:pick`, method: "POST" })
}

/**
 * @summary Upload file for question
 */
export const uploadQuestionFile = (
  questionId: string,
  uploadQuestionFileBody: Blob,
  params?: UploadQuestionFileParams,
) => {
  const formData = new FormData()
  formData.append("data", uploadQuestionFileBody)

  return apiRequest<UploadFileResponse>({
    url: `/mobile/questions/${questionId}/files`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    params,
  })
}

/**
 * @summary Create expertise info for current user
 */
export const createUserExpertise = (createUserExpertiseRequest: CreateUserExpertiseRequest) => {
  return apiRequest<void>({
    url: `/mobile/users/me/sections/expertise`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createUserExpertiseRequest,
  })
}

/**
 * @summary Get expertise info of current user
 */
export const getUserExpertise = () => {
  return apiRequest<GetUserExpertiseResponse[]>({
    url: `/mobile/users/me/sections/expertise`,
    method: "GET",
  })
}

/**
 * @summary Update expertise info of current user
 */
export const updateUserExpertise = (updateUserExpertiseRequest: UpdateUserExpertiseRequest) => {
  return apiRequest<void>({
    url: `/mobile/users/me/sections/expertise`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateUserExpertiseRequest,
  })
}

/**
 * @summary Get current user
 */
export const getCurrentUser = () => {
  return apiRequest<GetUserResponse>({ url: `/mobile/users/me`, method: "GET" })
}

/**
 * @summary Update current user
 */
export const updateUser = (updateUserRequest: UpdateUserRequest) => {
  return apiRequest<void>({
    url: `/mobile/users/me`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateUserRequest,
  })
}

/**
 * @summary Get current user contact
 */
export const getCurrentUserContacts = () => {
  return apiRequest<GetUserExpertiseResponse[]>({
    url: `/mobile/users/me/sections/contact`,
    method: "GET",
  })
}

/**
 * @summary Get notifications of current user
 */
export const getUserNotification = () => {
  return apiRequest<GetUserNotificationResponse[]>({
    url: `/mobile/users/me/sections/notification`,
    method: "GET",
  })
}

export type CreateQuestionEventResult = NonNullable<Awaited<ReturnType<typeof createQuestionEvent>>>
export type ListMobileQuestionEventsResult = NonNullable<
  Awaited<ReturnType<typeof listMobileQuestionEvents>>
>
export type CreateQuestionResult = NonNullable<Awaited<ReturnType<typeof createQuestion>>>
export type FinishConsultationResult = NonNullable<Awaited<ReturnType<typeof finishConsultation>>>
export type GetUserConfigurationsResult = NonNullable<
  Awaited<ReturnType<typeof getUserConfigurations>>
>
export type GetUserHighlightsResult = NonNullable<Awaited<ReturnType<typeof getUserHighlights>>>
export type ListCommunityQuestionsResult = NonNullable<
  Awaited<ReturnType<typeof listCommunityQuestions>>
>
export type ListMyQuestionsResult = NonNullable<Awaited<ReturnType<typeof listMyQuestions>>>
export type GetRecentQuestionsResult = NonNullable<Awaited<ReturnType<typeof getRecentQuestions>>>
export type PickQuestionResult = NonNullable<Awaited<ReturnType<typeof pickQuestion>>>
export type UploadQuestionFileResult = NonNullable<Awaited<ReturnType<typeof uploadQuestionFile>>>
export type CreateUserExpertiseResult = NonNullable<Awaited<ReturnType<typeof createUserExpertise>>>
export type GetUserExpertiseResult = NonNullable<Awaited<ReturnType<typeof getUserExpertise>>>
export type UpdateUserExpertiseResult = NonNullable<Awaited<ReturnType<typeof updateUserExpertise>>>
export type GetCurrentUserResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>
export type UpdateUserResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
export type GetCurrentUserContactsResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserContacts>>
>
export type GetUserNotificationResult = NonNullable<Awaited<ReturnType<typeof getUserNotification>>>
