/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type {
  CreateQuestionInput,
  Question,
  QuestionOutput,
  UploadFileForQuestionBody,
  UploadFileForQuestionParams,
  UploadQuestionFileResponse,
} from "./models"
import { customInstance } from "../api/api"

export const createQuestion = (createQuestionInput: CreateQuestionInput) => {
  return customInstance<void>({
    url: `/question`,
    method: "post",
    headers: { "Content-Type": "application/json" },
    data: createQuestionInput,
  })
}

export const getQuestionConfigurations = () => {
  return customInstance<void>({ url: `/question/configurations`, method: "get" })
}

export const getQuestionById = (id: string) => {
  return customInstance<QuestionOutput>({ url: `/question/${id}`, method: "get" })
}

export const getQuestionByUser = (user: string) => {
  return customInstance<QuestionOutput>({ url: `/question/user/${user}`, method: "get" })
}

export const listPublicAcceptedQuestions = () => {
  return customInstance<Question[]>({ url: `/question/list/public`, method: "get" })
}

export const listMyQuestions = () => {
  return customInstance<Question[]>({ url: `/question/list/mine`, method: "get" })
}

export const getAgencyPortal = () => {
  return customInstance<void>({ url: `/agency-portal`, method: "get" })
}

export const uploadFileForQuestion = (
  questionId: string,
  uploadFileForQuestionBody: UploadFileForQuestionBody,
  params: UploadFileForQuestionParams,
) => {
  const formData = new FormData()
  formData.append("file", uploadFileForQuestionBody.file)

  return customInstance<UploadQuestionFileResponse>({
    url: `/file/question/${questionId}`,
    method: "post",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    params,
  })
}

export const acceptQuestion = (id: string) => {
  return customInstance<void>({ url: `/question/${id}/accept`, method: "post" })
}

export type CreateQuestionResult = NonNullable<Awaited<ReturnType<typeof createQuestion>>>
export type GetQuestionConfigurationsResult = NonNullable<
  Awaited<ReturnType<typeof getQuestionConfigurations>>
>
export type GetQuestionByIdResult = NonNullable<Awaited<ReturnType<typeof getQuestionById>>>
export type GetQuestionByUserResult = NonNullable<Awaited<ReturnType<typeof getQuestionByUser>>>
export type ListPublicAcceptedQuestionsResult = NonNullable<
  Awaited<ReturnType<typeof listPublicAcceptedQuestions>>
>
export type ListMyQuestionsResult = NonNullable<Awaited<ReturnType<typeof listMyQuestions>>>
export type GetAgencyPortalResult = NonNullable<Awaited<ReturnType<typeof getAgencyPortal>>>
export type UploadFileForQuestionResult = NonNullable<
  Awaited<ReturnType<typeof uploadFileForQuestion>>
>
export type AcceptQuestionResult = NonNullable<Awaited<ReturnType<typeof acceptQuestion>>>
