/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { CreateQuestionEventRequest } from "./createQuestionEventRequest"
import type { CreateQuestionEventVoiceCalledInputType } from "./createQuestionEventVoiceCalledInputType"

export type CreateQuestionEventVoiceCalledInput = CreateQuestionEventRequest & {
  $type: CreateQuestionEventVoiceCalledInputType
  content?: string | null
}
