/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type CreateQuestionEventVoiceCalledInputType =
  (typeof CreateQuestionEventVoiceCalledInputType)[keyof typeof CreateQuestionEventVoiceCalledInputType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuestionEventVoiceCalledInputType = {
  VoiceCalled: "VoiceCalled",
} as const
