/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type CreateQuestionEventVideoCalledInputType =
  (typeof CreateQuestionEventVideoCalledInputType)[keyof typeof CreateQuestionEventVideoCalledInputType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuestionEventVideoCalledInputType = {
  VideoCalled: "VideoCalled",
} as const
