/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type CreateQuestionEventFileAttachedInputType =
  (typeof CreateQuestionEventFileAttachedInputType)[keyof typeof CreateQuestionEventFileAttachedInputType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuestionEventFileAttachedInputType = {
  FileAttached: "FileAttached",
} as const
