/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { SupportLevel } from "./supportLevel"

export interface CreateQuestionRequest {
  communityShareAgreement?: boolean | null
  priorityId?: string | null
  questionCategoryIds?: string[] | null
  supportLevel?: SupportLevel
  title?: string | null
}
