/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { QuestionCategoryDescription } from "./questionCategoryDescription"
import type { QuestionCategoryTitle } from "./questionCategoryTitle"

export interface QuestionCategory {
  createdOn?: string
  description?: QuestionCategoryDescription
  id?: string | null
  modifiedOn?: string
  title?: QuestionCategoryTitle
}
