/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { QuestionPriorityDescription } from "./questionPriorityDescription"
import type { TimeSpan } from "./timeSpan"
import type { QuestionPriorityPriorityMetaData } from "./questionPriorityPriorityMetaData"
import type { QuestionPriorityTitle } from "./questionPriorityTitle"

export interface QuestionPriority {
  createdOn?: Date
  description?: QuestionPriorityDescription
  duration?: TimeSpan
  id?: string | null
  key?: string | null
  modifiedOn?: Date
  priorityMetaData?: QuestionPriorityPriorityMetaData
  rank?: number
  title?: QuestionPriorityTitle
}
