/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { QuestionResponder } from "./questionResponder"
import type { QuestionStatus } from "./questionStatus"
import type { SupportLevel } from "./supportLevel"

export interface Question {
  communityShareAgreement?: boolean | null
  createdByUserId?: string | null
  createdOn?: string
  id?: string | null
  modifiedOn?: string
  priorityId?: string | null
  questionCategoryIds?: string[] | null
  responder?: QuestionResponder
  status?: QuestionStatus
  supportLevel?: SupportLevel
  title?: string | null
}
