/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export interface TimeSpan {
  readonly days?: number
  readonly hours?: number
  readonly microseconds?: number
  readonly milliseconds?: number
  readonly minutes?: number
  readonly nanoseconds?: number
  readonly seconds?: number
  ticks?: number
  readonly totalDays?: number
  readonly totalHours?: number
  readonly totalMicroseconds?: number
  readonly totalMilliseconds?: number
  readonly totalMinutes?: number
  readonly totalNanoseconds?: number
  readonly totalSeconds?: number
}
