/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { SupportLevel } from "./supportLevel"

export interface CreateQuestionInput {
  questionCategoryIds?: string[] | null
  supportLevel?: SupportLevel
  title?: string | null
}
