/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { QuestionCategory } from "./questionCategory"

export interface GetQuestionConfigurationsResponse {
  questionCategories?: QuestionCategory[] | null
}
