/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { QuestionStatus } from "./questionStatus"
import type { SupportLevel } from "./supportLevel"

export interface Question {
  createdByUserId?: string | null
  createdOn?: string
  id?: string | null
  modifiedOn?: string
  questionCategoryIds?: string[] | null
  status?: QuestionStatus
  supportLevel?: SupportLevel
  title?: string | null
}
