/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export interface QuestionCategory {
  createdOn?: string
  description?: string | null
  id?: string | null
  modifiedOn?: string
  title?: string | null
}
