/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { CreateQuestionEventRequest } from './createQuestionEventRequest';
import type { CreateQuestionEventMessageSentInput } from './createQuestionEventMessageSentInput';
import type { CreateQuestionEventStatusChangedInput } from './createQuestionEventStatusChangedInput';
import type { CreateQuestionEventFileAttachedInput } from './createQuestionEventFileAttachedInput';
import type { CreateQuestionEventVoiceCalledInput } from './createQuestionEventVoiceCalledInput';
import type { CreateQuestionEventVideoCalledInput } from './createQuestionEventVideoCalledInput';
import type { QuestionEventReacted } from './questionEventReacted';

export type CreateQuestionEventBody =
  | CreateQuestionEventRequest
  | CreateQuestionEventMessageSentInput
  | CreateQuestionEventStatusChangedInput
  | CreateQuestionEventFileAttachedInput
  | CreateQuestionEventVoiceCalledInput
  | CreateQuestionEventVideoCalledInput
  | QuestionEventReacted;
