/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { CreateQuestionEventRequest } from './createQuestionEventRequest';
import type { CreateQuestionEventVoiceCalledRequestType } from './createQuestionEventVoiceCalledRequestType';

export type CreateQuestionEventVoiceCalledRequest =
  CreateQuestionEventRequest & {
    $type: CreateQuestionEventVoiceCalledRequestType;
    content?: string | null;
  };
