/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type CreateQuestionEventVideoCalledRequestType =
  (typeof CreateQuestionEventVideoCalledRequestType)[keyof typeof CreateQuestionEventVideoCalledRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuestionEventVideoCalledRequestType = {
  VideoCalled: 'VideoCalled',
} as const;
