/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type CreateQuestionEventVoiceCalledRequestType =
  (typeof CreateQuestionEventVoiceCalledRequestType)[keyof typeof CreateQuestionEventVoiceCalledRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuestionEventVoiceCalledRequestType = {
  VoiceCalled: 'VoiceCalled',
} as const;
