/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { CreateQuestionEventRequest } from './createQuestionEventRequest';
import type { CreateQuestionEventMessageSentRequest } from './createQuestionEventMessageSentRequest';
import type { CreateQuestionEventStatusChangedRequest } from './createQuestionEventStatusChangedRequest';
import type { CreateQuestionEventFileAttachedRequest } from './createQuestionEventFileAttachedRequest';
import type { CreateQuestionEventVoiceCalledRequest } from './createQuestionEventVoiceCalledRequest';
import type { CreateQuestionEventVideoCalledRequest } from './createQuestionEventVideoCalledRequest';
import type { CreateQuestionEventReactedRequest } from './createQuestionEventReactedRequest';

export type CreateQuestionEventBody =
  | CreateQuestionEventRequest
  | CreateQuestionEventMessageSentRequest
  | CreateQuestionEventStatusChangedRequest
  | CreateQuestionEventFileAttachedRequest
  | CreateQuestionEventVoiceCalledRequest
  | CreateQuestionEventVideoCalledRequest
  | CreateQuestionEventReactedRequest;
