/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type CreateQuestionEventMessageSentRequestType =
  (typeof CreateQuestionEventMessageSentRequestType)[keyof typeof CreateQuestionEventMessageSentRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuestionEventMessageSentRequestType = {
  MessageSent: 'MessageSent',
} as const;
