/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type CreateQuestionEventFileAttachedRequestType =
  (typeof CreateQuestionEventFileAttachedRequestType)[keyof typeof CreateQuestionEventFileAttachedRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuestionEventFileAttachedRequestType = {
  FileAttached: 'FileAttached',
} as const;
