/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export interface CreateUserRequest {
  email?: string | null;
  userName?: string | null;
}
