/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type CreateQuestionEventReactedRequestType =
  (typeof CreateQuestionEventReactedRequestType)[keyof typeof CreateQuestionEventReactedRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuestionEventReactedRequestType = {
  EventReacted: 'EventReacted',
} as const;
