/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { CreateQuestionEventRequest } from './createQuestionEventRequest';
import type { CreateQuestionEventStatusChangedInputType } from './createQuestionEventStatusChangedInputType';
import type { QuestionStatus } from './questionStatus';
import type { CreateQuestionEventStatusChangedInputStatusMetaData } from './createQuestionEventStatusChangedInputStatusMetaData';

export type CreateQuestionEventStatusChangedInput =
  CreateQuestionEventRequest & {
    $type: CreateQuestionEventStatusChangedInputType;
    previousStatusChangedEventId?: string | null;
    questionStatus?: QuestionStatus;
    statusMetaData?: CreateQuestionEventStatusChangedInputStatusMetaData;
  };
