/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { ExpertiseType } from './expertiseType';

export interface CreateUserExpertiseRequest {
  expertiseType?: ExpertiseType;
  metaData?: string | null;
  title?: string | null;
}
