/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export interface GetUserResponse {
  firstName?: string | null;
  headline?: string | null;
  lastName?: string | null;
  profilePictureBlobLocation?: string | null;
  userName?: string | null;
}
