/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { QuestionBriefSection } from './questionBriefSection';
import type { CategoryBriefSection } from './categoryBriefSection';

export interface GetUserHighlightsResponse {
  expertExclusive: QuestionBriefSection;
  matchProfile: QuestionBriefSection;
  popularCategories: CategoryBriefSection;
  recent: QuestionBriefSection;
}
