/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type MobileQuestionEventMessageSentType =
  (typeof MobileQuestionEventMessageSentType)[keyof typeof MobileQuestionEventMessageSentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MobileQuestionEventMessageSentType = {
  MessageSent: 'MessageSent',
} as const;
