/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { SortingType } from './sortingType';
import type { QuestionStatus } from './questionStatus';
import type { SupportLevel } from './supportLevel';

export interface QueryQuestionsRequest {
  applyPagination?: boolean;
  categories?: string[] | null;
  createdAtSortingType?: SortingType;
  exceptIds?: string[] | null;
  limit?: number;
  mine?: boolean | null;
  myConsultation?: boolean | null;
  other?: boolean | null;
  prioritySorting?: SortingType;
  projectQuestionBrief?: boolean;
  queryIndex?: number | null;
  status?: QuestionStatus;
  statuses?: QuestionStatus[] | null;
  supportLevel?: SupportLevel;
}
