/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type QuestionEventReactedType =
  (typeof QuestionEventReactedType)[keyof typeof QuestionEventReactedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionEventReactedType = {
  EventReacted: 'EventReacted',
} as const;
