/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export interface QuestionConsultant {
  attachmentIds?: string[] | null;
  conclusion?: string | null;
  createdOn?: string;
  user?: string | null;
}
