/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export interface QuestionBrief {
  categories?: string[] | null;
  createdAt?: string;
  createdBy?: string | null;
  price?: string | null;
  saved?: boolean;
  title?: string | null;
}
