/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { QuestionAction } from './questionAction';

export interface QuestionPermissions {
  actions?: QuestionAction[] | null;
  directChatTargetUserId?: string | null;
}
