/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type SortingType = (typeof SortingType)[keyof typeof SortingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortingType = {
  Ascending: 'Ascending',
  Descending: 'Descending',
} as const;
