/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type SupportLevel = (typeof SupportLevel)[keyof typeof SupportLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupportLevel = {
  Community: 'Community',
  Expert: 'Expert',
  Agency: 'Agency',
} as const;
