/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { Gender } from './gender';

export interface UpdateUserRequest {
  firstName?: string | null;
  gender?: Gender;
  headline?: string | null;
  lastName?: string | null;
}
