/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { CategoryBrief } from "./categoryBrief"

export interface CategoryBriefSection {
  data: CategoryBrief[]
}
