/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { CreateQuestionEventRequest } from "./createQuestionEventRequest"
import type { CreateQuestionEventFileAttachedRequestType } from "./createQuestionEventFileAttachedRequestType"

export type CreateQuestionEventFileAttachedRequest = CreateQuestionEventRequest & {
  $type: CreateQuestionEventFileAttachedRequestType
  blobLocation?: string | null
  fileName?: string | null
  fileType?: string | null
}
