/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { CreateQuestionEventRequest } from "./createQuestionEventRequest"
import type { CreateQuestionEventMessageSentInputType } from "./createQuestionEventMessageSentInputType"

export type CreateQuestionEventMessageSentInput = CreateQuestionEventRequest & {
  $type: CreateQuestionEventMessageSentInputType
  content?: string | null
}
