/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type CreateQuestionEventMessageSentInputType =
  (typeof CreateQuestionEventMessageSentInputType)[keyof typeof CreateQuestionEventMessageSentInputType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuestionEventMessageSentInputType = {
  MessageSent: "MessageSent",
} as const
