/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { CreateQuestionEventRequest } from "./createQuestionEventRequest"
import type { CreateQuestionEventVideoCalledRequestType } from "./createQuestionEventVideoCalledRequestType"

export type CreateQuestionEventVideoCalledRequest = CreateQuestionEventRequest & {
  $type: CreateQuestionEventVideoCalledRequestType
  blobLocation?: string | null
  endedAt?: Date
  startedAt?: Date
}
