/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type ExpertiseType = (typeof ExpertiseType)[keyof typeof ExpertiseType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExpertiseType = {
  Education: "Education",
  Certification: "Certification",
  WorkExperience: "WorkExperience",
} as const
