/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export enum Gender {
  Male = "Male",
  Female = "Female",
  Other = "Other",
}
