/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { QuestionCategory } from "./questionCategory"
import type { QuestionPriority } from "./questionPriority"

export interface GetQuestionConfigurationsResponse {
  email?: string | null
  questionCategories?: QuestionCategory[] | null
  questionPriorities?: QuestionPriority[] | null
  userId?: string | null
}
