/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export interface GetUserResponse {
  email?: string | null
  firstName?: string | null
  headline?: string | null
  id?: string | null
  lastName?: string | null
  profilePictureBlobLocation?: string | null
  userName?: string | null
}
