/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { NotificationType } from "./notificationType"

export interface GetUserNotificationResponse {
  description?: string | null
  isRead?: boolean
  notificationType?: NotificationType
  title?: string | null
}
