/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { User } from "./user"

export interface MobileQuestionEvent {
  _id?: string | null
  $type: string
  createdAt?: Date
  user?: User
}
