/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export enum NotificationType {
  MessageReplied = "MessageReplied",
  QuestionAnswered = "QuestionAnswered",
}
