/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { QuestionCategoryResponseDescription } from "./questionCategoryResponseDescription"
import type { QuestionCategoryResponseTitle } from "./questionCategoryResponseTitle"

export interface QuestionCategoryResponse {
  description: QuestionCategoryResponseDescription
  key: string
  title: QuestionCategoryResponseTitle
}
