/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { QuestionPriorityResponseDescription } from "./questionPriorityResponseDescription"
import type { TimeSpan } from "./timeSpan"
import type { QuestionPriorityResponsePriorityMetaData } from "./questionPriorityResponsePriorityMetaData"
import type { QuestionPriorityResponseTitle } from "./questionPriorityResponseTitle"

export interface QuestionPriorityResponse {
  description: QuestionPriorityResponseDescription
  duration: TimeSpan
  key: string
  priorityMetaData: QuestionPriorityResponsePriorityMetaData
  rank: number
  title: QuestionPriorityResponseTitle
}
