/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export interface QuestionBrief {
  categories: string[]
  createdBy: string
  createdOn: string
  id: string
  price: string
  title: string
}
