/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { QuestionConsultant } from "./questionConsultant"
import type { QuestionPermissions } from "./questionPermissions"
import type { QuestionStatus } from "./questionStatus"
import type { SupportLevel } from "./supportLevel"

export interface Question {
  communityShareAgreement?: boolean | null
  consultant?: QuestionConsultant
  createdByUserId?: string | null
  createdOn?: Date
  id?: string | null
  modifiedOn?: Date
  permissions?: QuestionPermissions
  priorityId?: string | null
  queryIndex?: number
  questionCategoryIds?: string[] | null
  status?: QuestionStatus
  supportLevel?: SupportLevel
  title?: string | null
}
