/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export type QuestionAction = (typeof QuestionAction)[keyof typeof QuestionAction]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QuestionAction = {
  TakeConsultation: "TakeConsultation",
  GoToConversation: "GoToConversation",
} as const
