/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */

export enum SupportLevel {
  Community = "Community",
  Expert = "Expert",
  Agency = "Agency",
}
