/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { Gender } from "./gender"

export interface UpdateUserRequest {
  firstName?: string | null
  gender?: Gender
  headline?: string | null
  lastName?: string | null
}
