/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * Tranchy Ask Api Documentation
 * OpenAPI spec version: v1
 */
import type { ExpertiseType } from "./expertiseType"

export interface UpdateUserExpertiseRequest {
  expertiseType?: ExpertiseType
  id?: string | null
  metaData?: string | null
  title?: string | null
}
