/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Tranchy.Ask.API
 * OpenAPI spec version: 1.0
 */

export * from './buyCoffeeInput';
export * from './buyCoffeeOutput';
export * from './createQuestionInput';
export * from './questionOutput';