name: dev:agency-portal

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/Frontend/**"
env:
  NPM_CONFIG_FORCE: true
  NPM_CONFIG_LEGACY_PEER_DEPS: true
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_SEA_07587C700 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: /github/workspace/src/Frontend/tranchy
          app_build_command: "npm run build:agencyportal"
          output_location: /github/workspace/src/Frontend/tranchy/dist/apps/agencyportal
